# Generated by Django 3.0.4 on 2020-03-18 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yfcase', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='case',
            old_name='registeredmarketpricetext',
            new_name='registration_market_price_text',
        ),
        migrations.RemoveField(
            model_name='case',
            name='foreclosure_record',
        ),
        migrations.RemoveField(
            model_name='case',
            name='registration_map',
        ),
        migrations.RemoveField(
            model_name='case',
            name='registration_market_price',
        ),
        migrations.RemoveField(
            model_name='case',
            name='registration_photo',
        ),
    ]
