# Generated by Django 3.0.4 on 2020-03-18 01:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yfcase', '0002_auto_20200317_1435'),
    ]

    operations = [
        migrations.CreateModel(
            name='Land',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('landnumber', models.CharField(max_length=100)),
                ('landurl', models.CharField(max_length=100)),
                ('landarea', models.DecimalField(decimal_places=2, max_digits=7)),
                ('landholdingpointperson', models.IntegerField(default=0)),
                ('landholdingpointall', models.IntegerField(default=0)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yfcase.Case')),
            ],
        ),
    ]
