# Generated by Django 3.0.4 on 2020-03-24 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yfcase', '0003_auto_20200318_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='other_address',
            field=models.CharField(max_length=20, verbose_name='地址'),
        ),
    ]
