# Generated by Django 3.0.4 on 2020-03-18 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yfcase', '0004_auto_20200318_0948'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='other_address',
            field=models.CharField(default='', max_length=200, verbose_name='地址'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='case',
            name='casenumber',
            field=models.CharField(max_length=100, verbose_name='案號'),
        ),
        migrations.AlterField(
            model_name='case',
            name='city',
            field=models.CharField(max_length=20, verbose_name='縣市'),
        ),
        migrations.AlterField(
            model_name='case',
            name='section',
            field=models.CharField(max_length=20, verbose_name='段'),
        ),
        migrations.AlterField(
            model_name='case',
            name='small_section',
            field=models.CharField(max_length=20, verbose_name='小段'),
        ),
        migrations.AlterField(
            model_name='case',
            name='township',
            field=models.CharField(max_length=20, verbose_name='鄉鎮區'),
        ),
        migrations.AlterField(
            model_name='land',
            name='landarea',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='地坪(平方公尺)'),
        ),
        migrations.AlterField(
            model_name='land',
            name='landholdingpointall',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='所有持分'),
        ),
        migrations.AlterField(
            model_name='land',
            name='landholdingpointperson',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='個人持分'),
        ),
        migrations.AlterField(
            model_name='land',
            name='landnumber',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='地號'),
        ),
        migrations.AlterField(
            model_name='land',
            name='landurl',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='謄本'),
        ),
    ]
